### ISSUE TITLE
Failed to load PostCSS config: Unexpected token p in JSON

### ISSUE THREAD

**Issue by pReya** [tajo/ladle#205]
**Describe the bug**

When I run `npx ladle serve` in my project, I get a build error from Vite regarding a PostCSS config.

**Reproduction**

My project is pretty standard: TypeScript, React, Tailwind, Parcel 2 (all latest version). My PostCSS `.postcssrc` is also pretty basic:

```
{
  plugins: {
    tailwindcss: {}
  }
}
```

```
[plugin:vite:css] Failed to load PostCSS config (searchPath: /Users/user/Code/website-frontend): [SyntaxError] Unexpected token p in JSON at position 4
SyntaxError: Unexpected token p in JSON at position 4
    at JSON.parse (<anonymous>)
    at noExt (file:///Users/user/Code/website-frontend/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:18276:22)
    at Object.search (file:///Users/user/Code/website-frontend/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:18367:44)
    at async resolvePostcssConfig (file:///Users/user/Code/website-frontend/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:42378:22)
    at async compileCSS (file:///Users/user/Code/website-frontend/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:42146:27)
    at async TransformContext.transform (file:///Users/user/Code/website-frontend/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:41769:55)
    at async Object.transform (file:///Users/user/Code/website-frontend/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:35284:30)
    at async loadAndTransform (file:///Users/user/Code/website-frontend/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:39803:29)
/Users/user/Code/website-frontend/node_modules/@ladle/react/lib/app/ladle.css


```

More about [troubleshooting](https://ladle.dev/docs/troubleshooting).

**Environment**

 - OS: Mac OS latest
 - Browser Firefox latest

**Comment by pReya** [comment]
Apparently .postcssrc gets treated as json, so you need to make sure all keys are in quotes. I changed my `.postcssrc` to `.postcssrc.json` and changed the content to:

```
{
  "plugins": {
    "tailwindcss": {}
  }
}
```
