### ISSUE TITLE
Yarn Workspace not working

### ISSUE THREAD

**Issue by joshmedeski** [tajo/ladle#279]
**Describe the bug**

When I run `ladle serve` on an app inside a yarn workspace it fails to start.

**Reproduction**

```
yarn ui
yarn run v1.22.18
$ yarn ladle serve
$ /Users/joshmedeski/repos/nutiliti/node_modules/.bin/ladle serve
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:742:3)
    at tryReadSync (node:fs:442:20)
    at Object.readFileSync (node:fs:488:19)
    at hasWorkspacePackageJSON (file:///Users/joshmedeski/repos/nutiliti/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62054:37)
    at searchForWorkspaceRoot (file:///Users/joshmedeski/repos/nutiliti/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62082:9)
    at searchForWorkspaceRoot (file:///Users/joshmedeski/repos/nutiliti/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62088:12)
    at searchForWorkspaceRoot (file:///Users/joshmedeski/repos/nutiliti/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62088:12)
    at searchForWorkspaceRoot (file:///Users/joshmedeski/repos/nutiliti/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62088:12)
    at searchForWorkspaceRoot (file:///Users/joshmedeski/repos/nutiliti/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62088:12)
    at resolveServerOptions (file:///Users/joshmedeski/repos/nutiliti/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:62428:22) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
✨  Done in 0.48s.
```

The dependencies are installed int he root node_module directory of the yarn workspace.

**Environment**

- OS: macOS Monterey
- Browser: not applicable
- Version `^0.10.2`

**Comment by tajo** [comment]
Can you create a repro with https://ladle.dev/new?

**Comment by joshmedeski** [comment]
Here's my attempt, but I don't see the same issue https://stackblitz.com/edit/ladle-xrzumb

**Comment by tajo** [comment]
Yea, that works for me. You can try create a repo? Can't really look into this without a reproduction.
