### ISSUE TITLE
vite-plugin-react-swc and ladle

### ISSUE THREAD

**Issue by phaistonian** [tajo/ladle#294]
**Is your feature request related to a problem? Please describe.**

Vite 4x. brought [react-plugin-swc](https://github.com/vitejs/vite/blob/v4.0.0/packages/vite/CHANGELOG.md#new-react-plugin-using-swc-during-development) plugin.

However, when enabling it, Ladle does not work because, apparently, esbuild and its configuration is ignored, and so `.ts` files used by the ladle are not transpired.

See [caveats](https://github.com/vitejs/vite-plugin-react-swc#caveats) for more context.

**Describe the solution you'd like**
Ladle should work with the new plugin :)

**Comment by tajo** [comment]
> esbuild and its configuration is ignored, and so .ts files used by the ladle are not transpired

Ladle doesn't use any esbuild configuration. What exactly is breaking?

**Comment by phaistonian** [comment]
@tajo It seems the `.ts` files used to drive Ladle are not being transpiled. It only happens when opting for the new plugin.

I guess it's easy to reproduce using the react-plugin-swc instead of the default one.

**Comment by charsboo** [comment]
`package.json`:

```json
{
  "dependencies": {
    "@ladle/react": "^2.4.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "@vitejs/plugin-react-swc": "^3.0.0",
    "typescript": "^4.9.3",
    "vite": "^4.0.0"
  }
}
```

Terminal:

```sh
% npx ladle serve
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension. (x2)
6:58:35 PM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /Users/<user>/<project>/node_modules/@ladle/react/lib/app/src/addons/theme.tsx?v=f248edb0:41:16
  39 |          <span className="ladle-addon-tooltip">
  40 |            {globalState.theme === ThemeState.Light ? darkText : lightText}
  41 |          </span>
     |                 ^
  42 |          <label>
  43 |            Switch to{" "}
      at formatError (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
      at TransformContext.error (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
      at TransformContext.transform (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37078:22)
      at async Object.transform (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:30)
      at async loadAndTransform (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:29)
```

Browser:

```text
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
/Users/<user>/<project>/node_modules/@ladle/react/lib/app/src/addons/theme.tsx:41:16
39 |          <span className="ladle-addon-tooltip">
40 |            {globalState.theme === ThemeState.Light ? darkText : lightText}
41 |          </span>
   |                 ^
42 |          <label>
43 |            Switch to{" "}
    at formatError (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
    at TransformContext.error (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
    at TransformContext.transform (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37078:22)
    at async Object.transform (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:30)
    at async loadAndTransform (file:///Users/<user>/<project>/node_modules/@ladle/react/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:29
```

The file, `node_modules/@ladle/react/lib/app/src/addons/theme.tsx`, in VS Code:

<img width="690" alt="Screenshot 2023-01-09 at 7 08 03 PM" src="https://user-images.githubusercontent.com/46468051/211432698-3b486418-ee52-4c07-b96d-650fae644604.png">

```sh
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

**Comment by lianghx-319** [comment]
I got this issue too.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/27187946/213108121-7250a335-3956-4c8f-bc8f-b172e25bbec6.png">

**Comment by mgcrea** [comment]
Would be nice to support this, can easily be reproduced:

```sh
pnpm create @mgcrea/app -t react-ts test-ladle
cd test-ladle
pnpm add @react/ladle
pnpm ladle serve
```

Meanwhile I patched it with this:

```patch
diff --git a/lib/cli/vite-dev.js b/lib/cli/vite-dev.js
index eacd9c3311da967fe749ff04fd930a21292c1e6a..0fe7fc4c9120486fe4a73ada433c9fbc4958abc4 100644
--- a/lib/cli/vite-dev.js
+++ b/lib/cli/vite-dev.js
@@ -40,6 +40,9 @@ const bundler = async (config, configFolder) => {
         middlewareMode: true,
       },
     });
+    if (viteConfig.plugins[0].some(({name}) => name === 'vite:react-swc')) {
+      viteConfig.plugins[0] = (await import('@vitejs/plugin-react')).default();
+    }
     const vite = await createServer(viteConfig);
     const { moduleGraph, ws } = vite;
     app.head("*", async (_, res) => res.sendStatus(200));
```

**Comment by yann-combarnous** [comment]
@tajo , any reason files in `@ladle/react/lib/app/src/` are not compiled to js? I guess the react-swc plugin expects files in node_modules to be pre-compiled., and not to have to convert TSX=>JS there

**Comment by phaistonian** [comment]
@tajo When switching to SWC plugin, I get this:

`Error: Can't find an instance of @vitejs/plugin-react. You should apply this plugin to make mdx work.`

I can't find a way to disable support for `.mdx` or some other way to fix this issue.

Ideas?

**Comment by tajo** [comment]
Try `2.7.0`

**Comment by phaistonian** [comment]
Thank you. The new version solved one — but now this one has come up:

![CleanShot 2023-02-15 at 09 19 36@2x](https://user-images.githubusercontent.com/796530/218959082-66ce9535-ee49-4973-a35b-c3bbb0148a1a.png)

It might be something on my part, but I am not quite sure.

**Comment by phaistonian** [comment]
Yeah - it was something on my part, after all (a custom plugin).

False alarm :)
