### ISSUE TITLE
`ladle serve` error: "Failed to resolve force included dependency: react/jsx-dev-runtime"

### ISSUE THREAD

**Issue by nathanshelly** [tajo/ladle#61]
Thanks for making this tool! Excited to see the performance improvements the blog post touts.

I tried testing it out as a drop-in for Storybook in one of our projects and see the following error message. Any idea what might be going wrong? The closest relevant issue I see is [this one](https://github.com/vitejs/vite/issues/5642) from last November (which you happened to comment on) but theoretically that is now fixed so not sure if it's related.

```
❯ yarn add --dev @ladle/react
...
❯ DEBUG=ladle* yarn ladle serve
yarn run v1.22.17
$ /Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook/node_modules/.bin/ladle serve
  ladle:cli Starting serve command +0ms
  ladle:cli CLI theme: undefined +1ms
  ladle:cli CLI stories: undefined +0ms
  ladle:cli CLI port: undefined +0ms
  ladle:cli CLI open: undefined +0ms
  ladle:cli No custom config found. +4ms
  ladle:cli Final config:
  ladle:cli {
  ladle:cli   "stories": "src/**/*.stories.{js,jsx,ts,tsx}",
  ladle:cli   "root": "/Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook",
  ladle:cli   "defaultStory": "",
  ladle:cli   "babelPresets": [],
  ladle:cli   "babelPlugins": [],
  ladle:cli   "define": {},
  ladle:cli   "envPrefix": "VITE_",
  ladle:cli   "resolve": {
  ladle:cli     "alias": {}
  ladle:cli   },
  ladle:cli   "optimizeDeps": {
  ladle:cli     "include": []
  ladle:cli   },
  ladle:cli   "addons": {
  ladle:cli     "control": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": {}
  ladle:cli     },
  ladle:cli     "theme": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": "light"
  ladle:cli     },
  ladle:cli     "mode": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": "full"
  ladle:cli     },
  ladle:cli     "rtl": {
  ladle:cli       "enabled": true,
  ladle:cli       "defaultState": false
  ladle:cli     },
  ladle:cli     "ladle": {
  ladle:cli       "enabled": true
  ladle:cli     }
  ladle:cli   },
  ladle:cli   "serve": {
  ladle:cli     "open": "**Default**",
  ladle:cli     "port": 61000,
  ladle:cli     "define": {}
  ladle:cli   },
  ladle:cli   "build": {
  ladle:cli     "out": "build",
  ladle:cli     "sourcemap": false,
  ladle:cli     "baseUrl": "/",
  ladle:cli     "define": {}
  ladle:cli   }
  ladle:cli } +0ms
  ladle:cli Port set to: 61000 +3ms
Error: Failed to resolve force included dependency: react/jsx-dev-runtime
    at addManuallyIncludedOptimizeDeps (/Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook/node_modules/vite/dist/node/chunks/dep-19d0f55f.js:35966:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createOptimizeDepsRun (/Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook/node_modules/vite/dist/node/chunks/dep-19d0f55f.js:35721:13)
    at async runOptimize (/Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook/node_modules/vite/dist/node/chunks/dep-19d0f55f.js:54927:30)
    at async createServer (/Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook/node_modules/vite/dist/node/chunks/dep-19d0f55f.js:54961:9)
    at async bundler (file:///Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook/node_modules/@ladle/react/lib/cli/vite-dev.js:38:18)
    at async Command.serve (file:///Users/nathan/work/go/src/github.com/opendoor-labs/code/js/packages/bricks-storybook/node_modules/@ladle/react/lib/cli/serve.js:41:3)
```

**Comment by tajo** [comment]
What version of React do you use?

Can you create a repro? https://node.new/ladle

**Comment by nathanshelly** [comment]
React & `react-dom` version: `v16.8.6`. Looks like that version causes some issues. Here's a repro - https://stackblitz.com/edit/ladle-4w38rz?file=package.json

**Comment by tajo** [comment]
Ladle expects at least v16.10+ (older versions don't have jsx runtime). 

```json
"peerDependencies": {
    "react": ">=16.14.0",
    "react-dom": ">=16.14.0"
  },
```

The package manager should throw some errors/warning during the installation.

**Comment by iamzapata** [comment]
Hey, I read a blog post recently and was really excited to try this, coming from Storybook :S, this seems like a great replacement.  

I also came upon this issue, I'm using react and react-dom 18. 

In my case, the problem was that I was in the wrong directory. My stories were in another directory.
