### ISSUE TITLE
componentsRelativePath broken on Windows?

### ISSUE THREAD

**Issue by wojtekmaj** [tajo/ladle#80]
Steps to reproduce:

* Add basic Ladle setup: `@ladle/react`, `react`, `react-dom`.
* Create the simplest story under `src/button.jsx`.
* Add global provider under .ladle/components.js:
    ```js
    import React from 'react';
    
    export const Provider = ({ children, globalState }) => (
      <>
        <h1>Theme: {globalState.theme}</h1>
        {children}
      </>
    );
    ```
* Try to run the server.

```
[plugin:vite:import-analysis] Failed to resolve import "............ladle.ladlecomponents.js" from "..\node_modules\@ladle\react\lib\app\generated\generated-list.tsx". Does the file exist?
C:[/packages/node_modules/@ladle/react/lib/app/generated/generated-list.tsx:17:0]()
6  |  export let stories = { "button--default": { component: button$$default } };
7  |  export let config = {};
8  |  import { Provider as CustomProvider } from "............ladle.ladlecomponents.js";
   |                                              ^
9  |  export const Provider = CustomProvider;
10 |  if (import.meta.hot) {
    at formatError ([packages\node_modules\vite\dist\node\chunks\dep-a7fb482c.js:36237:46]())
    at TransformContext.error ([packages\node_modules\vite\dist\node\chunks\dep-a7fb482c.js:36233:19]())
    at normalizeUrl ([packages\node_modules\vite\dist\node\chunks\dep-a7fb482c.js:56981:26]())
    at processTicksAndRejections (node:internal[/process/task_queues:96:5]())
    at async TransformContext.transform ([packages\node_modules\vite\dist\node\chunks\dep-a7fb482c.js:57130:57]())
    at async Object.transform ([packages\node_modules\vite\dist\node\chunks\dep-a7fb482c.js:36474:30]())
    at async doTransform ([packages\node_modules\vite\dist\node\chunks\dep-a7fb482c.]()
```

This is the code that generates the relative path:
https://github.com/tajo/ladle/blob/70614da82b96fe58ddc8ebf824d74bcba7dbce67/packages/ladle/lib/cli/vite-plugin/generate/get-components-import.js#L59-L65

However, this results in 
```
'..\\..\\..\\..\\..\\..\\ladle\\.ladle\\components.js'
```
so this looks okay. However, the entire function returns

```
import {Provider as CustomProvider} from '..\..\..\..\..\..\ladle\.ladle\components.js';
```
! The double backslashes are gone.

So I monkey patched the code:

```diff
+      function escapePath(pathString) {
+        return pathString.replace(/\\/g, "\\\\");
+      }
-      return `import {Provider as CustomProvider} from '${componentsRelativePath}';\nexport const Provider = CustomProvider;\n`;
+      return `import {Provider as CustomProvider} from '${escapePath(componentsRelativePath)}';\nexport const Provider = CustomProvider;\n`;
```

and boom, it worked!

**Comment by wojtekmaj** [comment]
Duplicate of #67?
